### ISSUE TITLE
Default field in formhelper module.

### ISSUE THREAD

**Issue by AlexanderThaller** [bechtoldt/salt-modules#1]
It would be nice to have a way to define default values which are independent of the specific grain of a minion for the formhelper module.

Sometimes I have values that are the same on all operating systems and right now I have to copy past them to every operating system match I want to use. Right now I'm solving this by using a grain which is the same on all minions.

Maybe add a `_default` key which will be matched to all minions like so:

```
_default:
  version: '1.2.3'

os_family:
  FreeBSD:
    pkgname: 'pkgBSD'
  Debian:
    pkgname: 'pkgDebian'
```

Which would result in the following data:

```
FreeBSD:
  pkgname: 'pkgBSD'
  version: '1.2.3'
Debian:
  pkgname: 'pkgDebian'
  version: '1.2.3'
```

Would it be possible to have something like that or are there better/other options?

**Comment by arnisoph** [comment]
@AlexanderThaller sorry for the late reply!

I solve this by using an _existing_ grain that is present and equal on almost all of my minions, e.g. kernel=Linux

see https://github.com/bechtoldt/saltstack-salt-formula/blob/master/states/defaults.yaml#L2

But since you seem to use several different operating systems I think it makes sense to implement it.

**Comment by arnisoph** [comment]
@AlexanderThaller alright, after taking a deeper look at the code I just saw that the behaviour that you wish is already implemented. :)

Please take a look at https://github.com/bechtoldt/saltstack-skeleton-formula/blob/master/states/defaults.yaml#L2

Does it meet your requirements?

**Comment by AlexanderThaller** [comment]
Yes I used the default parameter as a workaround. Basically I just use a grain that is not existing on any machine like _default and then use the default parameter which is always used because the grain is never set. It feels bit ugly but its probably ok this way:

```
_default:
  default:
    mydefaultvalue: True
```

It works and its not to ugly.

Thx for your time.

**Comment by arnisoph** [comment]
@AlexanderThaller The name of the Grain should be irrelevant. Just use "kernel":

```
kernel:
  default:
    mydefaultvalue: True
```

**Comment by AlexanderThaller** [comment]
Ah is default always used? I was under the impression that it is only used if there is no value matched like a switch statement:

```
kernel:
  Linux:
    mykernelis: Linux
  default:
   mykernelis: DontKnow
```

Maybe I misunderstood.
